VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsBookmarkdata"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' しおりデータ一時保存用
Public lngPage As Long
Public strDIrectory00 As String
Public strDIrectory01 As String
Public strDIrectory02 As String
Public strDIrectory03 As String
Public strDIrectory04 As String
Public strDIrectory05 As String
Public strDIrectory06 As String
Public strDIrectory07 As String
Public strDIrectory08 As String
Public strDIrectory09 As String
